name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: reuters-graphics/action-workflows/.github/workflows/changesets-release.yaml@main
    secrets: inherit
    with:
      publish_docs: true
